### ISSUE TITLE
Clockwork Mechanism Variant 1 giving Credits always in Simulacrum

### ISSUE THREAD

**Issue by WolfoIsBestWolf** [Zenithrium/vanillaVoid#24]
Gives the first stack director credits minus the per stack bonus. ie: if you have 60 first stack 20 second stack in settings you get 40 credits even tho you got 0.

To fix just put it in a if itemcount > 1.

Also idk where to put actual item feedback so i'll just here so;
For Variant 0 I think it'd be good if the items dropped on stage start instead of just being given to you between stages. Wasn't a fan of variant 0 because I kinda just didn't realize I was even getting items or what Items I was getting.

**Comment by Zenithrium** [comment]
>Also idk where to put actual item feedback so i'll just here so;
For Variant 0 I think it'd be good if the items dropped on stage start instead of just being given to you between stages. Wasn't a fan of variant 0 because I kinda just didn't realize I was even getting items or what Items I was getting. 
this was the original intention for that variant, i just got lazy and never changed it. i'll try get that in soon
as well as the bug fix.. oopsies on that!

**Comment by Zenithrium** [comment]
Should have fixed the bug here. I'll make it drop items in the future, sorry
